# Generated by Django 6.0.5 on 2026-05-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='laudos/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
