# Generated by Django 6.0.5 on 2026-05-17 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('protocolos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='perito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos_gerados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laudo',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='laudo', to='protocolos.protocolo'),
        ),
    ]
