# Generated by Django 6.0.5 on 2026-05-17 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocolos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='perito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
