# Generated by Django 6.0.5 on 2026-05-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='status',
            field=models.CharField(choices=[('ABT', 'Aberto'), ('TRM', 'Em Trâmite'), ('FIN', 'Finalizado')], default='TRM', max_length=3),
        ),
    ]
