# Generated by Django 6.0.5 on 2026-05-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_alter_protocolo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='obs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='prioridade',
            field=models.CharField(choices=[('NOR', 'Normal'), ('URG', 'Urgente'), ('MUR', 'Muito Urgente')], default='NOR', max_length=3),
        ),
    ]
